FROM openjdk:12-alpine
COPY ./build/libs/service-gateway-0.0.1.jar /usr/app/
WORKDIR /usr/app

ENV GATEWAY_SERVICE_PORT 8080

ENV DISCOVERY_SERVICE_URL http://discovery:Passw0rd@host.docker.internal:8090/eureka/

ENTRYPOINT ["java", "-jar", "service-gateway-0.0.1.jar"]