FROM openjdk:12-alpine
COPY ./build/libs/service-gateway-0.0.1.jar /usr/app/
WORKDIR /usr/app

ENV GATEWAY_SERVICE_PORT 8080

ENV DISCOVERY_SERVICE_URL http://host.docker.internal:8090/eureka/

ENV DATABASE_USERNAME root
ENV DATABASE_PASSWORD password
ENV DATABASE_URL jdbc:mysql://host.docker.internal:3306/com.zbutwialypiernik.flixage

ENTRYPOINT ["java", "-jar", "service-gateway-0.0.1.jar"]