version: '2.3'

services:
  gateway:
    depends_on:
      - database
      - discovery
    build:
      context: service-gateway
      dockerfile: dockerfile
    ports:
      - "8080:8080"
  discovery:
    depends_on:
      - database
    build:
      context: service-discovery
      dockerfile: dockerfile
    ports:
      - "8090:8090"
  authentication:
    depends_on:
      - database
      - discovery
    build:
      context: service-authentication
      dockerfile: dockerfile
    ports:
      - "8091:8091"
  resource:
    depends_on:
      - database
      - discovery
    volumes:
      - ./storage:/usr/app/storage
    build:
      context: service-resource
      dockerfile: dockerfile
    ports:
      - "8092:8092"
  admin:
    depends_on:
    - database
    - discovery
    volumes:
      - ./storage:/usr/app/storage
    build:
      context: service-admin
      dockerfile: dockerfile
    ports:
      - "8093:8093"

# External Dependencies
  database:
    image: mysql
    volumes:
      - ./docker-volumes/database/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: flixage # Default database
      MYSQL_USER: admin
      MYSQL_ROOT_PASSWORD: password