version: '2.3'

services:
  gateway:
    depends_on:
      - database
      - discovery
    build:
      context: gateway
      dockerfile: dockerfile
    ports:
      - "8080:8080"
  discovery:
    depends_on:
      - database
    build:
      context: discovery
      dockerfile: dockerfile
    ports:
      - "8090:8090"
  authentication:
    depends_on:
      - database
      - discovery
    build:
      context: authentication
      dockerfile: dockerfile
    ports:
      - "8091:8091"
  resource:
    depends_on:
      - database
      - discovery
    build:
      context: resource
      dockerfile: dockerfile
    ports:
      - "8092:8092"

# External Dependencies
  database:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: flixage
      MYSQL_USER: admin
      MYSQL_ROOT_PASSWORD: password