create table album (id varchar(255) not null, creation_time datetime(6), last_update_time datetime(6), name varchar(255) not null, thumbnail_id varchar(255), artist_id varchar(255), primary key (id));
create table artist (id varchar(255) not null, creation_time datetime(6), last_update_time datetime(6), name varchar(255) not null, thumbnail_id varchar(255), primary key (id));
create table playlist (id varchar(255) not null, creation_time datetime(6), last_update_time datetime(6), name varchar(255) not null, thumbnail_id varchar(255), owner_id varchar(255), primary key (id));
create table playlist_tracks (playlist_id varchar(255) not null, tracks_id varchar(255) not null);
create table thumbnail (id varchar(255) not null, file_id varchar(255), mime_type varchar(255), size bigint, primary key (id));
create table track (id varchar(255) not null, creation_time datetime(6), last_update_time datetime(6), name varchar(255) not null, duration bigint, file_id varchar(255), file_size bigint, genre varchar(255), thumbnail_id varchar(255), album_id varchar(255), artist_id varchar(255), album varchar(255), primary key (id));
create table user (id varchar(255) not null, creation_time datetime(6), last_update_time datetime(6), name varchar(255) not null, enabled bit, expired bit, expired_credentials bit, locked bit, password varchar(60) not null, role varchar(255), username varchar(32) not null, thumbnail_id varchar(255), primary key (id));
create table user_playlists (user_id varchar(255) not null, playlists_id varchar(255) not null);
create table user_saved_tracks (user_id varchar(255) not null, saved_tracks_id varchar(255) not null);
create table refresh_token (id varchar(255) not null, creation_time datetime(6), last_update_time datetime(6), expire_time bigint, is_blacklisted bit, user_id varchar(255), primary key (id));
alter table playlist_tracks add constraint UK_2tatis33rvb9t3b0c98bt5dhc unique (tracks_id);
alter table user add constraint UK_sb8bbouer5wak8vyiiy4pf2bx unique (username);
alter table user_playlists add constraint UK_pf9n3qc8blwiyet930dqadcc8 unique (playlists_id);
alter table album add constraint FK26e2bh13cmwmdtgp01g8u2k9p foreign key (thumbnail_id) references thumbnail (id);
alter table album add constraint FKmwc4fyyxb6tfi0qba26gcf8s1 foreign key (artist_id) references artist (id);
alter table artist add constraint FKq7i22c23o8ova6gnqkawvagfp foreign key (thumbnail_id) references thumbnail (id);
alter table playlist add constraint FKf62n8ink56voh4gh5odx49og foreign key (thumbnail_id) references thumbnail (id);
alter table playlist add constraint FKth9shh6b71k2k9f8sdtuedunf foreign key (owner_id) references user (id);
alter table playlist_tracks add constraint FKs1ti0pm4ttt0lkx5xi86iwxcb foreign key (tracks_id) references track (id);
alter table playlist_tracks add constraint FKdmojw87kwq7bpf4h9fas2tkyj foreign key (playlist_id) references playlist (id);
alter table track add constraint FKnw2jm90wd89vatbini02dr7io foreign key (thumbnail_id) references thumbnail (id);
alter table track add constraint FKaxm9pbgk7ptorfyk3o6911q05 foreign key (album_id) references album (id);
alter table track add constraint FKi28jadqiuqk1dlxtl0me7hqh2 foreign key (artist_id) references artist (id);
alter table track add constraint FKrdqpaxtar239vj2gngp8e5ujx foreign key (album) references album (id);
alter table user add constraint FKpe1ii6nxpggpgwsm0cog80f5t foreign key (thumbnail_id) references thumbnail (id);
alter table user_playlists add constraint FK98v0e2xhqevuoydgu4ape9wb4 foreign key (playlists_id) references playlist (id);
alter table user_playlists add constraint FKnbth738rquy45l3m0uhda4thn foreign key (user_id) references user (id);
alter table user_saved_tracks add constraint FK6kql7by8aa6uae4jj8dv65p3b foreign key (saved_tracks_id) references track (id);
alter table user_saved_tracks add constraint FKgvl661ucqwy92juwcxn97mbeh foreign key (user_id) references user (id);
alter table refresh_token add constraint FKfgk1klcib7i15utalmcqo7krt foreign key (user_id) references user (id);
