FROM openjdk:11-alpine
COPY ./build/libs/gateway-0.0.1.jar /usr/app/
WORKDIR /usr/app

ENV GATEWAY_SERVICE_ADDRESS host.docker.internal
ENV GATEWAY_SERVICE_PORT 8080

ENV DISCOVERY_SERVICE_ADDRESS host.docker.internal
ENV DISCOVERY_SERVICE_PORT 8091

EXPOSE ${GATEWAY_SERVICE_PORT}
ENTRYPOINT ["java", "-jar", "gateway-0.0.1.jar"]