FROM openjdk:9-alpine
COPY ./build/libs/resource-server-0.0.1.jar /usr/app/
WORKDIR /usr/app

ENV RESOURCE_SERVICE_ADDRESS host.docker.internal
ENV RESOURCE_SERVICE_PORT 8092

ENV GATEWAY_SERVICE_ADDRESS host.docker.internal
ENV GATEWAY_SERVICE_PORT 8080

ENV DISCOVERY_SERVICE_ADDRESS host.docker.internal
ENV DISCOVERY_SERVICE_PORT 8090

EXPOSE ${RESOURCE_SERVICE_PORT}

ENTRYPOINT ["java", "-jar", "resource-server-0.0.1.jar"]