FROM openjdk:12-alpine
COPY ./build/libs/resource-server-0.0.1.jar /usr/app/
WORKDIR /usr/app

ENV RESOURCE_SERVICE_ADDRESS host.docker.internal
ENV RESOURCE_SERVICE_PORT 8092

ENV GATEWAY_SERVICE_ADDRESS host.docker.internal
ENV GATEWAY_SERVICE_PORT 8080

ENV DISCOVERY_SERVICE_ADDRESS host.docker.internal
ENV DISCOVERY_SERVICE_PORT 8090

ENV DATABASE_USERNAME root
ENV DATABASE_PASSWORD password
ENV DATABASE_URL jdbc:mysql://host.docker.internal:3306/flixage

EXPOSE ${RESOURCE_SERVICE_PORT}

ENTRYPOINT ["java", "-jar", "resource-server-0.0.1.jar"]