FROM openjdk:12-alpine
COPY ./build/libs/service-discovery-0.0.1.jar /usr/app/
WORKDIR /usr/app

ENV DISCOVERY_SERVICE_PORT 8090

ENV DISCOVERY_SERVICE_USERNAME discovery
ENV DISCOVERY_SERVICE_PASSWORD Passw0rd

EXPOSE 8090

ENTRYPOINT ["java", "-jar", "service-discovery-0.0.1.jar"]