FROM openjdk:12-alpine
COPY ./build/libs/service-discovery-0.0.1.jar /usr/app/
WORKDIR /usr/app

ENV DISCOVERY_SERVICE_PORT 8090

ENV DATABASE_USERNAME root
ENV DATABASE_PASSWORD password
ENV DATABASE_URL jdbc:mysql://host.docker.internal:3306/flixage

EXPOSE 8090

ENTRYPOINT ["java", "-jar", "service-discovery-0.0.1.jar"]